# Generated by Django 3.2 on 2021-06-01 13:42

from django.db import migrations, models
import sysimibio.bibliography.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publication_year', models.CharField(blank=True, help_text='YYYY', max_length=4, verbose_name='Año de publicación')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Título')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Autor')),
                ('DOI', models.CharField(blank=True, max_length=30, verbose_name='DOI')),
                ('ISBN', models.CharField(blank=True, help_text='Ingresar ISBN sin guion ni puntos', max_length=13, validators=[sysimibio.bibliography.validators.validate_isbn], verbose_name='ISBN')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Palabras clave o tema')),
                ('ORCID', models.URLField(blank=True, verbose_name='Orcid (opcional)')),
                ('URL', models.URLField(blank=True, verbose_name='Url (opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('last_modification_at', models.DateTimeField(auto_now=True, verbose_name='Ultima modificación')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('imibio', models.BooleanField(default=False, verbose_name='Participación IMIBIO ?')),
                ('crossref', models.BooleanField(default=True, help_text='Si tiene referencias con DOI O ISBN marcar.', verbose_name='Tiene DOI/ISBN ?')),
            ],
        ),
    ]
