# Generated by Django 3.2 on 2022-02-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesListViewTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=50, verbose_name='Nombre científico')),
                ('occurrence', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'managed': False,
            },
        ),
    ]
