# Generated by Django 3.2 on 2021-06-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='ORCID',
            field=models.URLField(blank=True, verbose_name='ORCID (opcional)'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='URL',
            field=models.URLField(blank=True, verbose_name='URL (opcional)'),
        ),
    ]
