# Generated by Django 3.2 on 2021-09-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0005_occurrencelist_specieslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specieslist',
            name='other_fields_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
