# Generated by Django 3.2 on 2021-09-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0006_alter_specieslist_other_fields_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specieslist',
            name='other_fields_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='specieslist',
            name='scientific_name',
            field=models.CharField(max_length=50, verbose_name='Nombre científico'),
        ),
    ]
