# Generated by Django 3.2 on 2021-10-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0007_auto_20210922_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencelist',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occurrencelist',
            name='bibliography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliography.publication'),
        ),
    ]
