# Generated by Django 3.2 on 2021-10-28 13:32

from django.db import migrations, models
import sysimibio.imibio_tree_ecological_data.validators


class Migration(migrations.Migration):

    dependencies = [
        ('bibliography', '0009_auto_20211015_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencelist',
            name='latitude',
            field=models.FloatField(validators=[sysimibio.imibio_tree_ecological_data.validators.validate_lat], verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='occurrencelist',
            name='longitude',
            field=models.FloatField(validators=[sysimibio.imibio_tree_ecological_data.validators.validate_lon], verbose_name='Longitud'),
        ),
    ]
