# Generated by Django 3.1.3 on 2020-11-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imibio_occurrences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imibiooccurrence',
            options={'ordering': ('-created_at',), 'verbose_name': 'Ocurrencia', 'verbose_name_plural': 'Ocorrencias'},
        ),
        migrations.AlterField(
            model_name='imibiooccurrence',
            name='decimalLatitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='imibiooccurrence',
            name='decimalLongitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
