# Generated by Django 3.1.3 on 2020-12-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imibio_occurrences", "0002_auto_20201129_0344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="basisOfRecord",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="catalogNumber",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="clase",
            field=models.CharField(max_length=254, verbose_name="class"),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="collectionCode",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="county",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="family",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="genus",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="institutionCode",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="kingdom",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="locality",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="municipality",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="order",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="phylum",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="scientificName",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="imibiooccurrence",
            name="stateProvince",
            field=models.TextField(),
        ),
    ]
