# Generated by Django 3.1.3 on 2021-03-22 13:54

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imibio_occurrences', '0003_auto_20201208_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='imibiooccurrence',
            name='geom',
            field=djgeojson.fields.PointField(default=[0, 0]),
            preserve_default=False,
        ),
    ]
