# Generated by Django 3.1.3 on 2020-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TreeEcologicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('responsable', models.CharField(max_length=100)),
                ('acompanantes', models.CharField(max_length=100)),
                ('id_parcela', models.IntegerField()),
                ('id_arbol', models.IntegerField()),
                ('especie', models.CharField(max_length=100)),
                ('dap', models.FloatField()),
                ('dab', models.FloatField()),
                ('altura', models.FloatField()),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fotografia', models.BooleanField()),
                ('obs', models.TextField()),
                ('estado_arbol', models.CharField(max_length=100)),
                ('forma_vida', models.CharField(max_length=100)),
                ('clasificacion_sociologica', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
