# Generated by Django 3.1.3 on 2020-12-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imibio_tree_ecological_data", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="treeecologicaldata",
            name="fecha",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="treeecologicaldata",
            name="fotografia",
            field=models.URLField(null=True),
        ),
    ]
