# Generated by Django 3.1.3 on 2021-03-08 01:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("imibio_tree_ecological_data", "0008_auto_20210213_0207"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treeecologicaldata",
            name="staff",
        ),
        migrations.AddField(
            model_name="treeecologicaldata",
            name="staff",
            field=models.ManyToManyField(
                max_length=100,
                related_name="staff",
                to=settings.AUTH_USER_MODEL,
                verbose_name="acompanantes",
            ),
        ),
    ]
