# Generated by Django 3.1.3 on 2021-03-22 13:58

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imibio_tree_ecological_data', '0009_auto_20210308_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='geom',
            field=djgeojson.fields.PointField(blank=True),
        ),
        migrations.AlterField(
            model_name='tree',
            name='tree_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
