# Generated by Django 3.2 on 2021-08-02 13:24

from django.db import migrations, models
import django.db.models.deletion
import sysimibio.imibio_tree_ecological_data.validators


class Migration(migrations.Migration):

    dependencies = [
        ('imibio_tree_ecological_data', '0015_auto_20210728_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dap', models.FloatField(default='A1', help_text='cm', validators=[sysimibio.imibio_tree_ecological_data.validators.tree_dap_validation], verbose_name='DAP')),
                ('dab', models.FloatField(help_text='cm', verbose_name='DAB')),
                ('tree_height', models.FloatField(help_text='m', validators=[sysimibio.imibio_tree_ecological_data.validators.tree_height_validation], verbose_name='Altura del árbol')),
                ('phytosanitary_status', models.CharField(choices=[('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Muerto', 'Muerto')], default='Bueno', max_length=100)),
                ('sociological_classification', models.CharField(choices=[('Emergente', 'Emergente'), ('Dominante', 'Dominante'), ('Codominante', 'Codominante'), ('Intermedia', 'Intermedia'), ('Inferior suprimido', 'Inferior Suprimido'), ('Inferior sumergido', 'Supeior Sumergido')], default='Emergente', max_length=100, verbose_name='Clasificación sociologica')),
                ('obs', models.TextField(blank=True, verbose_name='Observaciones')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imibio_tree_ecological_data.fieldwork')),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imibio_tree_ecological_data.pictures')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imibio_tree_ecological_data.tree')),
            ],
            options={
                'verbose_name': 'Medición de árbol',
                'verbose_name_plural': 'Mediciones de árboles',
            },
        ),
    ]
