# Generated by Django 3.2 on 2022-05-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("imibio_tree_ecological_data", "0015_auto_20211028_0938"),
        ("imibio_tree_ecological_data", "0017_auto_20220526_1113"),
    ]

    operations = []
