# Generated by Django 3.2 on 2022-05-30 22:53

from django.db import migrations, models
import multiselectfield.db.fields
import sysimibio.imibio_tree_ecological_data.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "imibio_tree_ecological_data",
            "0018_merge_0015_auto_20211028_0938_0017_auto_20220526_1113",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="permanentparcel",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="informar en formato en grados decimales WGS84 - epsg4326",
                validators=[
                    sysimibio.imibio_tree_ecological_data.validators.validate_lat
                ],
                verbose_name="Latitud",
            ),
        ),
        migrations.AlterField(
            model_name="permanentparcel",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="informar en formato en grados decimales WGS84 - epsg4326",
                validators=[
                    sysimibio.imibio_tree_ecological_data.validators.validate_lon
                ],
                verbose_name="Longitud",
            ),
        ),
        migrations.AlterField(
            model_name="permanentparcel",
            name="plot_type",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[("Fiscal", "Fiscal"), ("Privado", "Privado")], max_length=14
            ),
        ),
    ]
